---
title: "EDA Report"
author: "Tiffany Jeung"
date: "May 6, 2018"
output: html_document
---

# Overview

The goal of this exploratory data analysis is to gain a basic overview of the data. The data in question is Donald Trump’s tweets (@realDonaldTrump) from 5/4/2009 - 5/5/2018. The dataset can be found, thanks of Michael Kearney and his package rtweet here: https://bit.ly/2Ha0UEF. I will also explore tweets from the Twitter accoutn foxandfriends. Tidied versions of these datasets may be found in the processed subdirectory of the data folder.

<br> 

#### Load Packages + Data
```{R, message = FALSE}
# Load packages
library(tidyverse)
library(lubridate)
library(rtweet)

# Load data
train_trump <- readRDS(file = "data/processed/train_trump.rds")
train_fox <- readRDS(file = "data/processed/train_fox.rds")
```

### @realDonaldTrump
Important dates: <br>
1. Trump announced candidacy for president June 16, 2015 <br>
2. Trump became president on Jan 20, 2017

<br>

Trump tweets a lot. Since March 2009, he's tweeted at least 37.5K times. Since becoming president, his Twitter account has become a news source and a point of fascination for the public and thus warrants a closer look.

<br> 
This dataset runs from May 4, 2009, until May 5, 2018. The training set (80 percent) has 28970 observations and the test set (20 percent) has the remainder. There are some missing values in interaction values (retweets and favorites), but at ~1000 tweets of 28970, I have discarded them for this EDA, as they should not make an enormous difference in the findings. The missing values are scattered across years.
<br> 

```{R}
# Missing values
rt <- train_trump %>% 
  arrange(desc(retweet_count)) %>% 
  select(retweet_count, created_at, text, favorite_count)

# 1070 missing retweet/favorite values
sum(is.na(rt$retweet_count))
sum(is.na(rt$favorite_count))

# Remove missing retweets counts
rt <- rt %>% 
  filter(!is.na(retweet_count) & !is.na(favorite_count))
```

<br>
As expected, becoming president bolstered Donald Trump's twitter fame. 
```{R, echo = FALSE}
# Select only tweets post presidency
rt_pres <- rt %>% 
  filter(created_at > "2017-01-20")

# Select pre-presidency tweets
rt_pre_pres <- rt %>% 
  filter(created_at < "2017-01-20")

# Select post-candidacy announcement tweets
rt_candidate <- rt %>% 
  filter(created_at > "2015-06-16")
```
```{R}
# Average retweets pre presidency
round(mean(rt_pre_pres$retweet_count), 0)
# Average retweets from presidency on
round(mean(rt_pres$retweet_count), 0)

# Average favorites pre presidency
round(mean(rt_pre_pres$favorite_count), 0)
# Average favorites from presidency on
round(mean(rt_pres$favorite_count), 0)

```

```{R, echo = FALSE}
# Trump's retweets have gained increasing attention over the past two years
ggplot(rt, aes(created_at, retweet_count)) +
  geom_point(alpha = 0.2) +
  ggtitle("Trump's Retweeted Counts over Time") +
  scale_y_continuous(name = "Retweets", labels = scales::comma) +
  scale_x_datetime(name = "Year") +
  geom_vline(xintercept = as.numeric()) +
  theme(plot.title = element_text(hjust = 0.5))
```

His climb appears catalyzed by his 2016 presidential campaign and peaked in both favorites and retweets in January 2017 (when he was inaugurated). He reached a similar retweet peak in January 2018, but nowhere near the same favorite peak during that time.
```{R, echo = FALSE}
# see tweet trend by month/year
rt_candidate <- rt_candidate %>% 
  mutate(month = month(created_at),
         year = year(created_at)) %>% 
  group_by(month, year) %>%
  summarise(rt_avg = mean(retweet_count),
            fav_avg = mean(favorite_count)) %>% 
  mutate(date = parse_date((paste0(year, "-", month)), "%Y-%m"))

# Retweet and favorite progression since candidacy by month
ggplot(rt_candidate, aes(x = date)) +
  geom_bar(aes(y = rt_avg), stat = "identity") +
  scale_x_date(name = "Date by Month", date_breaks = "3 months", date_labels = "%Y-%b") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(name = "Average Retweets", labels = scales::comma) +
  ggtitle("Average Retweets per Month since Candidacy Announcement") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.minor = element_blank())

ggplot(rt_candidate, aes(x = date)) +
  geom_bar(aes(y = fav_avg), stat = "identity") +
  scale_x_date(name = "Date by Month", date_breaks = "3 months", date_labels = "%Y-%b") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1), plot.title = element_text(hjust = 0.5), panel.grid.minor = element_blank()) +
  scale_y_continuous(name = "Average Favorites per Month", labels = scales::comma) +
  ggtitle("Average Favorites per Month since Candidacy Announcement")
```

<br> 
So when does he tweet? What's his strategy?
<br>

First, a quick look at his Twitter history
```{R, echo = FALSE}
# Use rtweet plot function to get a basic overview
ts_plot(train_trump, "week") +
  scale_x_datetime(name = "Year") +
  scale_y_continuous(name = "Number of Tweets") +
  ggtitle("Frequency of Trump Tweets by Week") 
```

<br>
Here, we can see one of Trump's well-documented habits: tweeting at 3 a.m. He heavily favors the evening, more frequently sending out tweets from 6-8 p.m.
```{R, echo = FALSE}
# What time of day does Trump usually tweet?
train_trump <- train_trump %>% 
  mutate(hour = hour(created_at))

train_trump %>%
  ggplot() +
  geom_bar(aes(hour)) +
  scale_x_continuous("Hour of the Day") +
  scale_y_continuous("Tweet Count") +
  ggtitle("Trump Tweets by the Hour") + 
  theme(plot.title = element_text(hjust = 0.5))
```

He also tends to follow the businessweek, with a large drop in tweets on the weekend.
```{R, echo = FALSE}
# What day of the week does he tweet most?
dow <- train_trump %>% 
  mutate(wday = wday(created_at, label = TRUE),
         year = year(created_at)) %>% 
  group_by(wday, year) %>% 
  summarise(n = n())

ggplot(dow, aes(wday, n)) +
  geom_bar(stat = "identity", aes(fill = year)) + 
  scale_x_discrete(name = "Number of Tweets") +
  scale_y_continuous(name = "Days of the Week") +
  ggtitle("Trump's Tweets by Day of the Week") +
  theme(plot.title = element_text(hjust = 0.5))
```

#### Trump Topics

Let's look into Trump's interactions and language style, as both can serve as indicators for topics he cares about. 
<br>

Trump uses both hashtags and @ tags, but seems to favor @ tags. He uses them in tandem in 10.7 percent, only the hashtag in 6.5 percent and only the @ tag in 58.6 percent of his tweets.
<br>

Unsurprisingly, many of the top tags are related to his campaign, including Trump16, MakeAmericaGreatAgain, and AmericaFirst. CelebApprentice his reality show, is suprisingly high. <br>
```{R, echo = FALSE}
mentions_tr <- train_trump %>% 
  select(created_at, hashtags, mentions_screen_name)

# What does he usually use # for? 
hashtag_list <- mentions_tr %>% 
  filter(!is.na(hashtags)) %>% 
  select(hashtags) %>% 
  unlist()

# There are 384 hashtags Trump uses more than once, and only 145 that he uses more than 3 times. Many are related to his presidential campaign, which is unsurprising.
freq_hashtags <- as.tibble(sort(table(hashtag_list), decreasing = TRUE)) %>% 
  filter(n > 30)

ggplot(freq_hashtags) + 
  geom_bar(aes(x = reorder(hashtag_list, -n), y = n), stat = "identity") +
  scale_x_discrete(name = "Hashtag") +
  scale_y_continuous(name = "Number of Uses") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  ggtitle("Top Hashtags Used by Trump")
```

<br>
Trump's @tags are also often politically minded, reference Barack Obama over 400 times and mentioning multiple news outlets, include foxandfriends, FoxNews, nytimes, and CNN.
```{R, echo = FALSE}
# Who does he typically mention?
mention_list <- mentions_tr %>% 
  filter(!is.na(mentions_screen_name)) %>% 
  select(mentions_screen_name) %>% 
  unlist()

# Trump actively uses the @ sign: 
# Discard first value, since that seems to be other people tagging Trump, not Trump using @ tags.
freq_mentions <- as.tibble(sort(table(mention_list), decreasing = TRUE)) %>% 
  filter(n > 50)
freq_mentions <- freq_mentions[-1, ]

# Plot
ggplot(freq_mentions) + 
  geom_bar(aes(x = reorder(mention_list, -n), y = n), stat = "identity") +
  scale_x_discrete(name = "Screenname Mentioned") +
  scale_y_continuous(name = "Number of Uses") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  ggtitle("Top @tags Used by Trump")
```
<br>
Note: although foxandfriends is in Trump's top @ tags, the reverse is not true.
```{R, echo = FALSE}
mention_list_fox <- train_fox %>% 
  filter(!is.na(mentions_screen_name)) %>% 
  select(mentions_screen_name) %>% 
  unlist()

# Discard first value, since that seems to be other people tagging fox, not fox using @ tags.
freq_mentions_fox <- as.tibble(sort(table(mention_list_fox), decreasing = TRUE)) 
freq_mentions_fox <- freq_mentions_fox[-1,] %>% head()

# Plot of most commonly used @ tags 
ggplot(freq_mentions_fox) + 
  geom_bar(aes(x = reorder(mention_list_fox, -n), y = n), stat = "identity") +
  scale_x_discrete(name = "Screenname Mentioned") +
  scale_y_continuous(name = "Number of Uses") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  ggtitle("Top @tags Used by foxandfriends")
```
<br>

On the topic of news, how about fake news? The phrase appears in his tweets 184 times. 
```{R, echo = FALSE}
# Filter for fake news tweets only
fakenews <- train_trump %>% 
  filter(str_detect(text, "fake news | FAKE NEWS | Fake News") == TRUE)

# Plot of fake news tweets by week
ts_plot(fakenews, "weeks") +
  scale_x_datetime(name = "Date", date_breaks = "month", date_labels = "%b %Y") +
  scale_y_continuous(name = "Count", breaks = seq(0, 13, 1)) +
  theme(axis.text.x = element_text(angle = 30, hjust = 1), plot.title = element_text(hjust = 0.5)) +
  ggtitle("Mentions of Fake News in Trump Tweets")
```

<br>

Trump's choice of all caps also reflects his political cares and drives, including "Make America Great Again" and multiple news outlets.
```{R, echo = FALSE}
# All-caps? 
# How frequently does he use all-caps?
allcaps_use <- train_trump %>% 
  select(created_at, all_caps, uppercase_first)

all_cap_list <- unlist(allcaps_use$all_caps) 

# What does he all-caps the most?
freq_allcaps <- as.tibble(sort(table(all_cap_list), decreasing = TRUE))  %>% 
  filter(n > 225)

# Plot of most commonly mentioned words
ggplot(freq_allcaps) +
  geom_bar(aes(x = reorder(all_cap_list, -n), y = n), stat = "identity") + 
  scale_x_discrete(name = "Top words in all-caps") +
  scale_y_continuous(name = "Use Count") +
  ggtitle("Top words used by Trump in All-Caps") +
  theme(plot.title = element_text(hjust = 0.5))
```
### @foxandfriends

<br>
An overview timeline of foxandfriends on Twitter:
```{R, echo = FALSE}
# FoxandFriends tweets over time
ts_plot(train_fox) +
  scale_x_datetime(name = "Date", date_breaks = "week", date_labels = "%b %d %Y") +
  scale_y_continuous(name = "Tweet Count") +
  ggtitle("Fox and Friends Tweets over Time") +
  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 30, hjust = 1))
```

Foxandfriends follows much more traditional business hours, although there are some tweets in the evenings.
```{R, echo = FALSE}
# What time of day do foxandfriends usually tweet?
train_fox <- train_fox %>% 
  mutate(hour = hour(created_at))

train_fox %>%
  ggplot() +
  geom_bar(aes(hour)) +
  scale_x_continuous("Hour of the Day") +
  scale_y_continuous("Tweet Count") +
  ggtitle("Foxandfriends Tweets by the Hour") + 
  theme(plot.title = element_text(hjust = 0.5))
```
<br>

Foxandfriends appears to slightly favor Tuesdays, but does not tweet absurdly more or less on a particular day.
```{R, echo = FALSE}
# What day of the week do they tweet most?
dow_fox <- train_fox %>% 
  mutate(wday = wday(created_at, label = TRUE)) %>% 
  group_by(wday) %>% 
  summarise(n = n())

ggplot(dow_fox, aes(wday, n)) +
  geom_bar(stat = "identity") + 
  scale_x_discrete(name = "Number of Tweets") +
  scale_y_continuous(name = "Days of the Week") +
  ggtitle("Foxandfriend's Tweets by Day of the Week") +
  theme(plot.title = element_text(hjust = 0.5))
```

